#!/bin/python3
import socket
import sys
import tkinter as tk
from tkinter import *
from tkinter import messagebox , filedialog
import tkinter.scrolledtext as ST
import tkinter.ttk as ttk
from ttkthemes import ThemedTk
import threading
from time import sleep
import datetime as dt

WIDTH = 800
HEIGHT = 400
running_socket = False

def server():
	global running_socket

	HOST = host.get()
	PORT = port.get()
	
	if( HOST == "" ) or ( PORT == "" ):
		ta.insert('insert','   Hostname & Portnumber not given so using default values.\nlocalhost @ 8888')
		HOST = "localhost"
		PORT = 8888
		
	if( running_socket == True ):
		ta.insert('insert','\n   A connection is already in progress\n')
		return	
	running_socket = True
	
	sct = socket.socket( socket.AF_INET , socket.SOCK_STREAM )	
	try:
		ta.delete( 0.0 , END )
		ta.insert( 'insert' , f'\n   Creating socket for --[ {HOST} ]--\n   Opening port --[ {PORT} ]--\n' )
		print( f'Creating socket @[ {HOST} ]\nOpening port [ {PORT} ]\n' )
		sct.bind( ( str(HOST) , int(PORT) ) )
		
	except socket.error as err_msg:
		running_socket = False
		ta.insert( 'insert' , f'\n\n   [ ✕ ] Server binding/creation error\n   {err_msg}\n' )
		print( f'\n\n   [ ✕ ] Server binding/creation error\n   {err_msg}\n' )
		sys.exit()

	ta.insert( 'insert' , '\n   [ i ] SocketOpen -> [ ✓ ]\n   [ i ] PortOpen -> [ ✓ ]\n' )
	sct.listen(2048)
	ta.insert( 'insert' , '   [ i ] Listening...\n\n' )

	while True:
		conn , address = sct.accept()
		ta.insert( 'insert' , '   [ i ] Connection established\n        from '+str(address)+' at [ ' + str(dt.datetime.now())+'] \n\n' )
		conn.send( bytes( "\nKonektimi ne server eshte i sukseshem\nMireseerdhe :)\n".encode("utf-8") ) )
		for i in range(0,5):
			conn.send( bytes( "\nData\n".encode("utf-8") ) )
			sleep(100)
	
	sct.close()
	print('Socket closed')

def init_server():
	ta.delete( 0.0 , END )
	thrd = threading.Thread(target=server)
	thrd.daemon = True
	thrd.start()
	
def close_server():
	global running_socket
	running_socket = False

# Code initialisation
try:	
	
	bg = "#1d1d1d"
	fg = "white"	
	
	window = ThemedTk()
	window.title("Server Information")
	window.geometry( str(WIDTH)+"x"+str(HEIGHT+30) )
	window.grid()
	
	style = ttk.Style()
	style.theme_use('breeze') # arc , radiance , black , breeze , equilux
	# style.configure( 'BW.TFrame' , foreground=fg, background=bg )
	
	tabs = ttk.Notebook(window)
	
	frame = ttk.Frame( tabs , width=WIDTH , height=HEIGHT ) #, style="BW.TFrame"
	frame2 = ttk.Frame( tabs , width=WIDTH , height=HEIGHT )
	info = ttk.Label( frame2 , text="\n\nMore information comming soon !" ).pack()
	
	host = tk.StringVar()
	port = tk.StringVar()
	
	host_label = ttk.Label( frame , text="Hostname" ).place(x=10,y=15)
	host_entry = ttk.Entry( frame , width=50 , textvariable=host ).place(x=10 , y=30)
	
	port_label = ttk.Label( frame , text="Port number" ).place(x=10,y=65)
	port_entry = ttk.Entry( frame , width=50 , textvariable=port ).place(x=10 , y=80)
	
	btn = ttk.Button( frame , text="\nStart Server\n" , command=init_server , width=21 ).place(x=11 , y=120)
	dicsonnect_btn = ttk.Button( frame , text="\nDisconnect\n" , command=close_server , width=21 ).place(x=202 , y=120)

	ta = ST.ScrolledText( frame , bg="white" , fg="black" , width=56 , height=28 )
	ta.insert('insert','\n   Insert host and port number\n   To start the server, click the "Start Server" button\n')
	ta.place(x=WIDTH/2-27,y=0)
	frame.pack()
	
	tabs.add(frame , text="Server")
	tabs.add(frame2 , text="More")
	tabs.pack()
	
	window.mainloop()

except Exception as e:
	print(e)
except KeyboardInterrupt as ke:
	messagebox.showinfo("Program information","Program stoped by user by KeyboardInterrupt")
	window.destroy()
	print("Stoped script")
	sys.exit()
